### ISSUE TITLE
[Android 9 - target SDK 28] Backbutton not working

### ISSUE THREAD

**Issue by fgarcia5** [apache/cordova-plugin-splashscreen#186]
Hello!

After implementing this plugin in my project, the backbutton listener breaks.

The bug has appeared in different users, you can see more details here: https://github.com/apache/cordova-android/issues/687

Does anyone know how to fix it? Thanks!

**Comment by MaximeLimone** [comment]
Hello,

I just find a little fix (or something that does the job), if i comment the line 103 in SpashScreen.java (getView().setVisibility(View.INVISIBLE);).

The back button work correctly.

**Comment by fgarcia5** [comment]
The fix has solved the problem in Android 9. We have also tested it in the other versions of Android and the backbutton works correctly.

Thank you very much!

**Comment by MBuchalik** [comment]
@fgarcia5 
Shouldn't we keep this issue open until it has been fixed in the plugin itself? If I am not mistaken, the issue still persists on master.

**Comment by fgarcia5** [comment]
It's right. The issue has been reopend.

Thanks, @MBuchalik

**Comment by akadebnath** [comment]
Thank you for your contribution. However, I am seeing the PR has not been merged yet. Canyou guys please do a little more to complete this. Thanks again for finding a solution.

**Comment by janpio** [comment]
PR #225 is ready to review, so I have to reproduce this: Plain Cordova app (created with `cordova create`) _without_ this plugin I should be able to use the back button to go back in the navigation, after adding the plugin the back button will not work correctly any more. Then with the PR branch it should work again - is this all correct?

**Comment by MBuchalik** [comment]
>  Plain Cordova app (created with cordova create) without this plugin I should be able to use the back button to go back in the navigation, after adding the plugin the back button will not work correctly any more. Then with the PR branch it should work again - is this all correct?

@janpio I believe this is correct! 👍 Most likely, you can use something like the code posted in https://github.com/apache/cordova-android/issues/687 to test this:

``` JS
document.addEventListener('deviceready', onDeviceReady, false);
function onDeviceReady() {   
    document.addEventListener('backbutton', onBackKeyDown, false);
}
function onBackKeyDown() {
    alert('The back button was pressed!');
}
```

@fgarcia5 Does this match your description from https://github.com/apache/cordova-android/issues/687 ?

**Comment by janpio** [comment]
Oh sorry, I missed that linked Cordova Android issue. That looks like a valid reproduction and I will try it (if I can get the Android 9 emulator to work for once...).

**Comment by heidji** [comment]
@janpio hey man, you're everywhere :D. Please merge this PR, it works like a charm..

**Comment by heidji** [comment]
@janpio This plugin breaks the back button override on the first page only for me, but after going to a different page the intended override kicks in.
This is mainly because Cordova doesn't even fire a backbutton event on that first page, only the "pause" event. The PR fixes everything..

**Comment by janpio** [comment]
The problem is that we don't really understand why #225, the disabling of the hiding of the webview, is needed. What changed in Android 9 that requires this?

Having a repro project would be awesome - my and our time is very limited so every minute not spent on trying to reproduce something can be spent in reviews.

**Comment by heidji** [comment]
@janpio here's the [demonstration app](https://github.com/heidji/splashscreen-backbutton-test)
run it on your emulator/device and press the back button after the app loads, the app will close which isn't intended since in the code I override the backbutton in the very beginning. go to a different tab however AND THEN press back and the override kicks in so the app won't close.

The project is created in Ionic and the system info is provided in the readme.

**Comment by evertson90** [comment]
Hi, any update on this issue?

**Comment by janpio** [comment]
Do you have additional insight why the existing code doesn't work on Android 9 @evertson90? Otherwise: Nobody seems to have posted any information regarding this, so we are not really too happy to just merged this :/

**Comment by nikolavuk** [comment]
How i solved this problem..

**Comment by heidji** [comment]
@janpio ok, regardless that the extended impact of this merge is unknown, now that the users here have presented a problem that still has no alternative solution to this PR, are the maintainers at all interested in finding a solution that pleases them or will they just leave it open like that?

**Comment by joy2012bd** [comment]
Same issue. Any suggestion? Commented the line 103, but not working.

**Comment by heidji** [comment]
@joy2012bd use this [pull request](https://github.com/apache/cordova-plugin-splashscreen/pull/225) in your project.

**Comment by burhanuddin-taha** [comment]
Hi  @heidji 
is there is any plan to merge above PR, and publish new plugin. 
Thanks for help

**Comment by heidji** [comment]
there is a way but it's too much at the moment. just replace the current splashscreen line in package.json with
`"cordova-plugin-splashscreen": "git+https://github.com/prageeth/cordova-plugin-splashscreen.git",`
let's pray the maintainers come to their senses soon 🙏

**Comment by IntellectBizMobility** [comment]
@heidji  The mentioned solution works if the first screen has got tab and you are developing an application with only the tab screens, But if your application has multiple screen, plugin from prageeth's fork is working only for the first screen and as soon as I moved from 1st Screen to 2nd Screen, the fix stop responding resulting in exit app. Please help.

**Comment by heidji** [comment]
I'm using Ionic3 and there i have a login screen and later I change the root to the tabs app. nothing crashes here, sorry.

**Comment by IntellectBizMobility** [comment]
@heidji Let me explain you more about the problem, if I am clicking any element or doing any action on the screen the application is behaving fine. but If i just navigate to screen B from A and click "back button" then the problem is occurring. have you tested the same way?

**Comment by heidji** [comment]
what do you mean by "navigate"?
aren't you using screen stack to navigate?

**Comment by IntellectBizMobility** [comment]
I have tried both by SetRoot method and push method. For Example:
this.navCtrl.push(location);
this.navCtrl.setRoot(location);

**Comment by heidji** [comment]
i don't know about this very specific case, but i use setRoot and modals normally, plus on my tabs app i use nested tabs and an extremely complex navigation scheme. maybe update your packages?

**Comment by joy2012bd** [comment]
> @joy2012bd use this [pull request](https://github.com/apache/cordova-plugin-splashscreen/pull/225) in your project.

I have tried this pull request. Not working. Same as before.

**Comment by IntellectBizMobility** [comment]
Issue resolved. In Android SDK 28, we have to use the splashscreen from the updated fork of Prageeth and also we cannot use native transition plugin in our application. Thank you guys.

**Comment by luigi37** [comment]
Same issue here. Sorted with
https://github.com/prageeth/cordova-plugin-splashscreen

would be great to merge the fix in master...

**Comment by brodybits** [comment]
Here is my understanding so far:

- using this plugin breaks functionality related to the back button on Android 9 / target SDK 28
- the issue is reproduced by @heidji in https://github.com/heidji/splashscreen-backbutton-test
- fix was proposed by @prageeth in PR #225
- people are using @prageeth fork until we get this resolved in master

@janpio had requested some more information to help us understand *why* we need to make this kind of a change for Android 9. This kind of information could give us some more confidence before merging PR #225. We are also not (yet) super confident that we can do this without breaking something else.

I hope we can get a member to do some more review and testing. Any pointers that could help guide one of us through the reproduction, testing, and review of the code would be extremely helpful.

In case we really drop the ball please feel free to ping us on the mailing list or Slack, see links in the footer of cordova.io

**Comment by koz1ma** [comment]
I was still having the back button issue even with prageeth fork, my fix was to replace getView().setVisibility(View.INVISIBLE); for getView().setVisibility(View.GONE); on file src/android/SplashScreen.java

**Comment by luigi37** [comment]
I recently add AdMob to my app and despite fix proposed by @prageeth in PR #225 still the backbutton is not working...
Note: is not a matter of code (same code, if I don't show the add, the backbutton works) but probably a matter of views as mentioned above
https://github.com/apache/cordova-plugin-splashscreen/issues/186#issuecomment-564891453

**Comment by luigi37** [comment]
A further  observation... if the banner is at top the backbutton does close the app (whatsever, 90% of the time, not sue why 10% it works), but if it's at the bottom, the backbutton works properly...

**Comment by biodiv** [comment]
I found out, that in my case, using

```
document.addEventListener('backbutton', function(event){
   onBackKeyDown() 
}, false);
```
works on Android 9, while

`document.addEventListener('backbutton', onBackKeyDown, false);`

does not.
I have no explanation for this behaviour, but maybe it helps someone.

**Comment by chengda** [comment]
> Hello,
> 
> I just find a little fix (or something that does the job), if i comment the line 103 in SpashScreen.java (getView().setVisibility(View.INVISIBLE);).
> 
> The back button work correctly.

thank u! I solved my problem with your method.

**Comment by 11digits** [comment]
I used this, and it works for me https://github.com/prageeth/cordova-plugin-splashscreen

**Comment by prageeth** [comment]
Hi, since the version of this plugin has been updated since I created the original PR (#225), I've also now created a new `branch` called `v6`, which pulls in all the latest changes from `apache/cordova-plugin-splashscreen#master`.

So for anyone who wants to use the latest version but also with the fix, can use this branch:
https://github.com/prageeth/cordova-plugin-splashscreen/tree/v6

I have intentionally left the master branch of my fork untouched to make sure anyone using that fork reference is not affected.

You can manually use this `v6` branch name or the individual commit `31ea5cf`.
```
// package.json
"cordova-plugin-splashscreen": "git+https://github.com/prageeth/cordova-plugin-splashscreen.git#v6",

// or config.xml
<plugin name="cordova-plugin-splashscreen" spec="https://github.com/prageeth/cordova-plugin-splashscreen.git#v6" source="git" />
```

**Comment by DavidBik** [comment]
I also have the issue with the back button breaking the app. 
If I remove the splashscreen plugin it works fine.

I have also tried @prageeth 's fork but it doesn't seem to work. Any help would be great.

**Comment by knight9999** [comment]
Hi. Could someone please try to improve following code in `SplashScreen.java` in cordova-plugin-splashscreen?

```
--- a/src/android/SplashScreen.java
+++ b/src/android/SplashScreen.java
@@ -194,6 +194,7 @@ public class SplashScreen extends CordovaPlugin {
         } else if ("spinner".equals(id)) {
             if ("stop".equals(data.toString())) {
                 getView().setVisibility(View.VISIBLE);
+                getView().requestFocus();
             }
         } else if ("onReceivedError".equals(id)) {
             this.spinnerStop();
```

**Comment by vadimwe** [comment]
Seems problem exists in "cordova-plugin-splashscreen": "^6.0.0"

**Comment by Tarekajaj** [comment]
Still facing this issue on
```
android 10
cordova-android 10.1.1
cordova-plugin-splashscreen 6.0.0
android-targetSdkVersion 29
```
is there any reliable fix so far?

**Comment by Tarekajaj** [comment]
> Still facing this issue on
> 
> ```
> android 10
> cordova-android 10.1.1
> cordova-plugin-splashscreen 6.0.0
> android-targetSdkVersion 29
> ```
> 
> is there any reliable fix so far?

Downloaded the master version 6.0.1-dev and the issue is resolved
